#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
STRINGS_PATH = File.join(ROOT, "strings.yaml")
SUPPORTED_LOCALES = %w[en ru].freeze

def load_strings_catalog
  catalog = YAML.load_file(STRINGS_PATH)
  strings = catalog.fetch("strings")
  unless strings.is_a?(Hash) && !strings.empty?
    raise "strings.yaml must define a non-empty `strings` mapping"
  end

  strings.each do |key, entry|
    unless key.is_a?(String) && key.match?(/\A[a-z0-9_]+\z/)
      raise "Invalid string key #{key.inspect}; use snake_case resource identifiers"
    end
    unless entry.is_a?(Hash)
      raise "Entry #{key.inspect} must be a locale map"
    end

    SUPPORTED_LOCALES.each do |locale|
      value = entry[locale]
      raise "Entry #{key.inspect} is missing locale #{locale.inspect}" unless value.is_a?(String)
    end
  end

  strings
end

def placeholder_names(value)
  value.scan(/%\{([a-z0-9_]+)\}/).flatten.uniq
end

def android_escape(value)
  placeholders = placeholder_names(value)
  formatted = value.gsub(/%\{([a-z0-9_]+)\}/) do
    name = Regexp.last_match(1)
    index = placeholders.index(name)
    raise "Unknown placeholder #{name.inspect} in #{value.inspect}" unless index

    "%#{index + 1}$s"
  end

  escaped = formatted
    .gsub("\\") { "\\\\" }
    .gsub("'") { "\\'" }
    .gsub("\"") { "\\\"" }
    .sub(/\A([@?])/) { "\\#{$1}" }
    .gsub("\n", "\\n")

  escaped
    .gsub("&", "&amp;")
    .gsub("<", "&lt;")
    .gsub(">", "&gt;")
end

def swift_escape(value)
  value
    .gsub("\\") { "\\\\" }
    .gsub("\"") { "\\\"" }
    .gsub("\n", "\\n")
end

def snake_to_camel(value)
  head, *tail = value.split("_")
  head + tail.map(&:capitalize).join
end

def generate_android(strings)
  {
    "values" => "en",
    "values-ru" => "ru",
  }.each do |directory, locale|
    output_path = File.join(ROOT, "apps/android/app/src/main/res", directory, "strings.xml")
    FileUtils.mkdir_p(File.dirname(output_path))

    body = strings.map do |key, entry|
      %(    <string name="#{key}">#{android_escape(entry.fetch(locale))}</string>)
    end.join("\n")

    File.write(
      output_path,
      <<~XML
        <resources>
        #{body}
        </resources>
      XML
    )
  end
end

def generate_swift(strings, output_path)
  FileUtils.mkdir_p(File.dirname(output_path))

  key_cases = strings.keys.map do |key|
    "    case #{snake_to_camel(key)} = \"#{key}\""
  end.join("\n")

  locale_maps = SUPPORTED_LOCALES.map do |locale|
    entries = strings.map do |key, entry|
      %(            "#{key}": "#{swift_escape(entry.fetch(locale))}")
    end.join(",\n")

    <<~SWIFT.chomp
      "<?=locale?>": [
      <?=entries?>
          ]
    SWIFT
      .gsub("<?=locale?>", locale)
      .gsub("<?=entries?>", entries)
  end.join(",\n        ")

  content = <<~SWIFT
    // Generated by scripts/generate_strings.rb. Do not edit by hand.
    import Foundation

    enum TrixStringKey: String, CaseIterable {
    #{key_cases}
    }

    enum TrixStrings {
        private static let translations: [String: [String: String]] = [
            #{locale_maps}
        ]

        static func text(
            _ key: TrixStringKey,
            replacements: [String: String] = [:],
            locale: Locale = .autoupdatingCurrent
        ) -> String {
            var value = lookup(key.rawValue, locale: locale) ?? key.rawValue
            for (token, replacement) in replacements {
                value = value.replacingOccurrences(of: "%{\\(token)}", with: replacement)
            }
            return value
        }

        private static func lookup(_ key: String, locale: Locale) -> String? {
            let languageCode = locale.identifier
                .replacingOccurrences(of: "_", with: "-")
                .split(separator: "-")
                .first
                .map(String.init) ?? "en"

            return translations[languageCode]?[key] ?? translations["en"]?[key]
        }
    }
    SWIFT

  File.write(output_path, content)
end

strings = load_strings_catalog
generate_android(strings)
generate_swift(strings, File.join(ROOT, "apps/ios/TrixiOS/Generated/TrixStrings.generated.swift"))
generate_swift(strings, File.join(ROOT, "apps/macos/Sources/TrixMac/Generated/TrixStrings.generated.swift"))
